"""Swap model architecture figures in project_report_v2.docx.

Replaces the text-heavy SVG-style boxes with the new visual-array PNGs
generated by scripts/regenerate_model_diagrams.py.
"""

from pathlib import Path

from docx import Document
from docx.oxml.ns import qn
from docx.shared import Inches, Emu

ROOT = Path(__file__).resolve().parent.parent
DOCX = ROOT / "project_report_v2.docx"
FIGS = ROOT / "report_figures_v3"

MAP = {
    "rId14": "fig06_mf_bpr_training.png",
    "rId16": "fig07_mf_bpr_inference.png",
    "rId17": "fig08_ncf_gmf.png",
    "rId18": "fig09_ncf_mlp.png",
    "rId19": "fig10_neumf.png",
    "rId21": "fig11_lightgcn_prop.png",
    "rId23": "fig12_lightgcn_training.png",
    "rId24": "fig13_cmf.png",
    "rId26": "fig14_emcdr.png",
    "rId28": "fig15_ptupcdr.png",
    "rId30": "fig16_sbert.png",
    "rId31": "fig17_sbert_cdr.png",
    "rId33": "fig18_cooc.png",
    "rId34": "fig19_cooc_rerank.png",
}

TARGET_WIDTH_IN = 6.0
EMU_PER_INCH = 914400


def main():
    from PIL import Image
    d = Document(str(DOCX))

    # Swap image data
    for rid, fname in MAP.items():
        new_path = FIGS / fname
        if not new_path.exists():
            print(f"  ! missing {fname}")
            continue
        rel = d.part.rels[rid]
        rel.target_part._blob = new_path.read_bytes()
        print(f"  ✓ {rid} ← {fname}")

    # Resize each inline image
    paragraphs_with_images = {}
    for i, p in enumerate(d.paragraphs):
        for blip in p._p.iter(qn('a:blip')):
            rid = blip.get(qn('r:embed'))
            if rid in MAP:
                paragraphs_with_images[i] = (rid, blip)

    for i, (rid, blip) in paragraphs_with_images.items():
        fname = MAP[rid]
        img = Image.open(FIGS / fname)
        w_px, h_px = img.size
        target_w_emu = int(TARGET_WIDTH_IN * EMU_PER_INCH)
        target_h_emu = int(target_w_emu * h_px / w_px)

        p = d.paragraphs[i]
        for extent in p._p.iter(qn('wp:extent')):
            extent.set('cx', str(target_w_emu))
            extent.set('cy', str(target_h_emu))
        for ext in p._p.iter(qn('a:ext')):
            ext.set('cx', str(target_w_emu))
            ext.set('cy', str(target_h_emu))

    d.save(str(DOCX))
    print(f"\nSaved {DOCX}")
    print(f"Swapped {len(MAP)} figures at {TARGET_WIDTH_IN}\" width")


if __name__ == "__main__":
    main()
